# Generated by Django 4.1.5 on 2023-03-01 19:52

from django.db import migrations, models
import django.db.models.deletion
import online_store.settings


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_cart_payed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('PayPal', 'PayPal'), ('Bank Transfer', 'BankTransfer'), ('Apple pay', 'ApplePay'), ('Google pay', 'GooglePay'), ('Credit card', 'CreditCard')], default=online_store.settings.PaymentMethods['CreditCard'], max_length=32)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('cart', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.cart')),
            ],
        ),
    ]
