# Generated by Django 4.1.5 on 2023-03-01 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_paymentdetail'),
        ('customer', '0003_paymentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
        ),
    ]
