# Generated by Django 4.1.5 on 2023-03-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_paymentdetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='user',
        ),
    ]
