# Generated by Django 4.1.5 on 2023-03-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_cart_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='payed',
            new_name='paid',
        ),
    ]
