# Generated by Django 4.1.5 on 2023-03-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_rename_payed_cart_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bought_items',
            field=models.JSONField(default=dict),
        ),
    ]
